// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIKOSH42QypJKkruwDrt6ZPbgto0CWkg',
    appId: '1:364090100955:web:aab1323b8ee9331e2d90fe',
    messagingSenderId: '364090100955',
    projectId: 'skillup-b8386',
    authDomain: 'skillup-b8386.firebaseapp.com',
    storageBucket: 'skillup-b8386.firebasestorage.app',
    measurementId: 'G-V7Q7PPN5T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuIi8L70L5GnoNMqYl6MfHRZA2l-qiIw',
    appId: '1:364090100955:android:f36ab0a8ebd110172d90fe',
    messagingSenderId: '364090100955',
    projectId: 'skillup-b8386',
    storageBucket: 'skillup-b8386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCihuzfQXamIG2e0wF2A7r4EA_19tiYn7Q',
    appId: '1:364090100955:ios:8f53defd988f08b42d90fe',
    messagingSenderId: '364090100955',
    projectId: 'skillup-b8386',
    storageBucket: 'skillup-b8386.firebasestorage.app',
    iosBundleId: 'com.skillup.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCihuzfQXamIG2e0wF2A7r4EA_19tiYn7Q',
    appId: '1:364090100955:ios:d1cc7cbf6439c6212d90fe',
    messagingSenderId: '364090100955',
    projectId: 'skillup-b8386',
    storageBucket: 'skillup-b8386.firebasestorage.app',
    iosBundleId: 'com.example.skillup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIKOSH42QypJKkruwDrt6ZPbgto0CWkg',
    appId: '1:364090100955:web:ca6cf193d9a4336b2d90fe',
    messagingSenderId: '364090100955',
    projectId: 'skillup-b8386',
    authDomain: 'skillup-b8386.firebaseapp.com',
    storageBucket: 'skillup-b8386.firebasestorage.app',
    measurementId: 'G-NH99SWVG0E',
  );
}
